### ISSUE TITLE
Make `mkdir` failure

### ISSUE THREAD

**Issue by scottwillmoore** [bmatzelle/gow#171]
I don't know what causes this issue, but hopefully you can help.

I installed gow so I could use Makefiles as I am learning `c`, but for some reason the command `mkdir` is not working right.

Whenever I run a Makefile that uses `mkdir -p <folder>` it throws `The syntax of the command is incorrect.` (Many Makefiles appear to use this). This of course is not true, because when using the `gow` tool `mkdir.exe` the arguments work perfectly fine. It is like it is using a different `mkdir` command.

I am using PowerShell, but when I swapped over to MSYS and executed the Makefile it works! I just want to know how the `make.exe` works. Does it have all these commands built in, or does it use PowerShell to execute the commands.

I thought if it uses PowerShell then I should check to see if PowerShell has a `mkdir` command, however it does not, I had a function defined somewhere, but I have since deleted all aliases and functions named `mkdir`.

Thoughts? I am a little unsure what to do know.

Update: just figured out maybe instead of pulling from PowerShell it pulls from windows `cmd`. Because `cmd` has a `MKDIR` command but no `rm` command, which explains why `rm` works but `mkdir` is not working, because `MKDIR` in `cmd` is taking precendence. Any ideas on how to fix this?

**Comment by HumanBlade** [comment]
There is some overlap between the UNIX style tool names and your default windows. Make is issuing a command to the console that your computer is looking for and finding the windows version. You can tell because windows mkdir/md has no flags/options.
The 'solution' is either to remove System32 from your path for the purpose of development, or to use fully qualified filenames... C:\Program Files(x86)\gow\bin\mkdir.exe.
Make also has aliasing, i believe, so that you can say name a utility with a simple association mkdir:C:\Program... Your ileage may vary however as i think the OS specific version may still override.
You may want to create a desktop user that has System32 removed from the path and use that account specifically for development.

**Comment by bytehead-** [comment]
The problem is not the system32 path.  Mkdir is an internal command for cmd.exe.  You can, however, just use the quoted name to ensure that you are executing the mkdir.exe.

"mkdir.exe" -p c:/I/do/not/care/what/I/make

works.

mkdir.exe -p c:\I\do\not\care\what\I\make

will not work.  In fact, just executing mkdir.exe will make a directory called .exe on whatever location you are currently sitting at.

So either do not use cmd.exe for anything (Powershell.exe has the same issues) by running sh.exe directly or inside cmd.exe, or just quote the exe name, and it will execute the exe file first without executing the internal command.

Of course, just executing "mkdir.exe" will find the first mkdir.exe, so you may want to do a which mkdir.exe to make sure you are executing the correct mkdir.exe.

**Comment by scottwillmoore** [comment]
Alright thanks for that, I believe moving to a non-unix based tool to learn `c` may be better, or using cygwin to emulate a UNIX based environment. I do not really wish to make my Makefile use "mkdir.exe" as I want my scripts to work across most platforms, but it looks like using a tool such as cmake or premake will do perfectly.
