### ISSUE TITLE
Not able to do backspace in vim

### ISSUE THREAD

**Issue by aniketgm** [bmatzelle/gow#258]
**Steps to Reproduce :**
1. Launch vim and start writing some text
2. Do backspace and you are able to do it.
3. Now goto next line and write some text and do backspace, again you will be able to do it.
4. Now goto first line, where there is some text and do backspace. Not able to backspace characters.
5. Goto next line, same issue. Now not able to backspace of any old text until you goto a new line and do backspace.

Is it possible to update gow with latest / stable vim version ?

Console: cmder (also tried with dos prompt, same issue)

**Comment by arafat-ar13** [comment]
This is something I faced when using the normal version of Vim too. You have to mainly edit your `.vimrc` file to solve this. Since the gow vim version too uses your default `.vimrc`, this might help. Put this in your `.vimrc` file:

`set backspace=indent,eol,start`

This helped to solve my issue and might help you too.
