### ISSUE TITLE
Clear Command

### ISSUE THREAD

**Issue by ghost** [bmatzelle/gow#55]
An easy feature that I'd really like, is adding the `clear` command - it could easily be done with a batch file (which is what I do on my machines) with the following:

```
@echo off
cls
```

Thoughts?

**Comment by ianchanning** [comment]
What is also useful is the clear command for bash. You can add this in by copying the clear file from msysgit but using /bin/bash instead of their /bin/sh:

```bash
#!/bin/bash
# Make the 'clear' command work, by invoking command.com/cmd.exe 'cls'

$COMSPEC //C cls
```

So in `Gow\bin` you have `clear.bat` and `clear` but they don't conflict as running `clear` in dos runs `clear.bat` and running `clear` in bash runs the `clear` file.

Note that its also possible to include the clear command in the `.bashrc` file but I think its better to have the specific file:
```bash
alias clear='printf "\033c"'
```

See the [SO answer][1] about this.

[1]: http://stackoverflow.com/a/20836284/327074
